/// Kind of test double generated by MockSyn.
public enum MockSynDoubleKind: Equatable, Sendable {
    /// A mock records calls and is primarily verification-oriented.
    case mock

    /// A stub is primarily response-oriented.
    case stub

    /// A spy records calls and can delegate to a wrapped implementation.
    case spy

    /// A hand-written fake that reuses MockSyn runtime helpers.
    case fake
}
